# Generated by Django 2.2.5 on 2019-09-10 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_cms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cms2017',
        ),
    ]
