# Generated by Django 2.2.5 on 2019-09-10 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_cms', '0003_cms2017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cms2017',
        ),
    ]
