# Generated by Django 2.2.5 on 2019-09-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_cms', '0006_regions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='regions',
        ),
    ]
