# Generated by Django 2.2.5 on 2019-09-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_cms', '0014_auto_20190910_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions2',
            name='accssbl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='amenits',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='atsm_tt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='cct_p_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='cct_pr_field',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='cct_prc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='condtns',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='cp_totl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='dcm_ttl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='dh_totl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='drcp_tt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='ds_totl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='eb_totl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='elc_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='hi_totl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='id_totl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='ii_totl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='inst_field',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='int_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='li_totl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='longitd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='md_totl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='n_ntrn_field',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='n_ntrnt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='nlc_scl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='noelec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='nowater',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='orgnl_l_field',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='orgnl_n_field',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='orgnl_w_field',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='p_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='pd_totl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='pwd_ttl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='regn_nm',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='rmtn_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='rmtns_field',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='rmtnss_field',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='schl_yr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='schol_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='shap_ar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='shi_scr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='shp_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='shp_ttl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='spch_tt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='stdnt_c_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='stdnt_c_field',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='stdnt_t_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='stdnt_t_field',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='totl_ml',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='ttl_fml',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='ttl_nrl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='ttl_rc_field',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='ttl_tch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='unnm_0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='vi_totl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='wcg_ttl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='wtr_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regions2',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
