# Generated by Django 2.2.5 on 2019-09-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_cms', '0022_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Remoteness', models.FloatField(default=0.6)),
                ('Percentage_CCT', models.FloatField(default=0.4)),
                ('Water_Access', models.FloatField(default=0.4)),
                ('Internet_Access', models.FloatField(default=0.3)),
                ('Electricity_Access', models.FloatField(default=0.3)),
                ('Student_Teacher_Ratio', models.FloatField(default=0.5)),
                ('Student_Classroom_Ratio', models.FloatField(default=0.5)),
            ],
        ),
    ]
