# Generated by Django 2.2.5 on 2019-09-13 13:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_cms', '0026_regions_simple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions_simple',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
